### ISSUE TITLE
Own Dataset

### ISSUE THREAD

**Issue by Henry831** [garvita-tiwari/sizer#2]
Thanks for your awesome work!
and i have a question about 
Can i use my own scan human mesh to create a smpl model ?
(the mesh have different actions)

**Comment by garvita-tiwari** [comment]
@Henry831 If you want to register SMPL model to your scans, you can refer to this work: https://github.com/bharat-b7/LoopReg.  or https://github.com/bharat-b7/IPNet/tree/master/smpl_registration

**Comment by Henry831** [comment]
> Thanks for your awesome work!
> and i have a question about
> Can i use my own scan human mesh to create a smpl model ?
> (the mesh have different actions)
